CAT-24489 Prepared to test docker-build-test-push template

diff --git a/.github/workflows/docker-build-push-template.yml b/.github/workflows/docker-build-push-template.yml
--- a/.github/workflows/docker-build-push-template.yml
+++ b/.github/workflows/docker-build-push-template.yml
@@ -1,4 +1,4 @@
-name: Template - Run Shell Command
+name: Template - Docker Build/Test/Push
 
 on:
   workflow_call:
@@ -9,12 +9,17 @@ on:
         required: true
       before_command:
         type: string
-        description: 'Run preparation commands before the commands'
+        description: '(Optional) Command to prepare the environment'
+        required: false
+        default: ''
+      test_command:
+        type: string
+        description: 'Command to test the docker image (runs inside the container)'
         required: false
         default: ''
       after_command:
         type: string
-        description: 'Run teardown commands after the commands'
+        description: '(Optional) Command to teardown the environment'
         required: false
         default: ''
       assume_aws_role:
@@ -61,6 +66,7 @@ jobs:
     runs-on: ubuntu-latest
     environment: ${{ inputs.env }}
     steps:
+      # Get code, permissions and set environment
       - name: Checkout code
         uses: actions/checkout@main
         with:
@@ -74,7 +80,7 @@ jobs:
           role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT }}:role/service/${{ vars.AWS_OIDC_ROLE }}
 
       - name: Login to Amazon ECR
-        if: success() && inputs.ecr_login == true
+        if: inputs.ecr_login == true
         uses: aws-actions/amazon-ecr-login@v1
 
       - name: Run preparation
@@ -82,28 +88,31 @@ jobs:
         id: before-command
         run: ${{ inputs.before_command }}
 
+
+      # Docker image build
+      - uses: ./.github/actions/slack-message
+        if: ${{ vars.SLACK_CHANNEL_ID }} != ''
+        id: slack-build
+        with:
+          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
+          token: ${{ secrets.SLACK_BOT_TOKEN }}
+          text: "[${{ env.APP_NAME }} ${{ inputs.env }}] Docker image build - Started"
+
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
   
       - name: Create and use a new builder instance
         run: |
           docker buildx create --name builder --use
-  
-      - uses: ./.github/actions/slack-message
-        if: always() && ${{ vars.SLACK_CHANNEL_ID }} != ''
-        id: slack
-        with:
-          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
-          token: ${{ secrets.SLACK_BOT_TOKEN }}
-          text: "[${{ vars.APP_NAME }} ${{ inputs.env }}] Building docker image"
 
-      - name: Build and push
+      - name: Build Docker image
         uses: docker/build-push-action@v5
+        id: build-image
         with:
           context: ${{ inputs.context }}
           file: ${{ inputs.dockerfile }}
-          push: true
-          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }}
+          load: true
+          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.APP_NAME }}:${{ inputs.image_test_tag }}
           builder: builder
           cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.APP_NAME }}:cache-${{ inputs.image_build_tag }}
           cache-to: type=registry,mode=max,image-manifest=true,oci-mediatypes=true,ref=${{ env.DOCKER_REGISTRY }}/${{ env.APP_NAME }}:cache-${{ inputs.image_build_tag }}
@@ -113,10 +122,64 @@ jobs:
         with:
           channel_id: ${{ vars.SLACK_CHANNEL_ID }}
           token: ${{ secrets.SLACK_BOT_TOKEN }}
-          text: "[${{ vars.APP_NAME }} ${{ inputs.env }}] Building docker image - complete"
-          status: ${{ steps.run-command.outcome }}
-          update: ${{ steps.slack.outputs.update }}
+          text: "[${{ env.APP_NAME }} ${{ inputs.env }}] Docker image build - Completed"
+          status: ${{ steps.build-image.outcome }}
+          update: ${{ steps.slack-build.outputs.update }}
 
+
+      # Docker image test
+      - uses: ./.github/actions/slack-message
+        if: ${{ vars.SLACK_CHANNEL_ID }} != ''
+        id: slack-test
+        with:
+          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
+          token: ${{ secrets.SLACK_BOT_TOKEN }}
+          text: "[${{ env.APP_NAME }} ${{ inputs.env }}] Docker image test - Started"
+
+      - name: Test Docker image
+        if: ${{ inputs.test_command }} != ""
+        id: test-image
+        run: |
+          docker run --rm ${{ inputs.image_test_tag }} ${{ inputs.test_command }}
+
+      - uses: ./.github/actions/slack-message
+        if: always() && ${{ vars.SLACK_CHANNEL_ID }} != ''
+        with:
+          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
+          token: ${{ secrets.SLACK_BOT_TOKEN }}
+          text: "[${{ env.APP_NAME }} ${{ inputs.env }}] Docker image build - Completed"
+          status: ${{ steps.test-image.outcome }}
+          update: ${{ steps.slack-test.outputs.update }}
+        
+
+      # Docker image push
+      - uses: ./.github/actions/slack-message
+        if: ${{ vars.SLACK_CHANNEL_ID }} != ''
+        id: slack-push
+        with:
+          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
+          token: ${{ secrets.SLACK_BOT_TOKEN }}
+          text: "[${{ env.APP_NAME }} ${{ inputs.env }}] Docker image push - Started"
+  
+      - name: Build and push
+        uses: docker/build-push-action@v6
+        id: push-image
+        with:
+          platforms: linux/amd64,linux/arm64
+          push: true
+          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.APP_NAME }}:${{ inputs.image_build_tag }}
+
+      - uses: ./.github/actions/slack-message
+        if: always() && ${{ vars.SLACK_CHANNEL_ID }} != ''
+        with:
+          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
+          token: ${{ secrets.SLACK_BOT_TOKEN }}
+          text: "[${{ env.APP_NAME }} ${{ inputs.env }}] Docker image push - Complete"
+          status: ${{ steps.push-image.outcome }}
+          update: ${{ steps.slack-push.outputs.update }}
+
+
+      # Teardown and job end status
       - name: Run teardown
         if: ( success() || failure() ) && inputs.after_command != ''
         id: after-command
@@ -127,11 +190,21 @@ jobs:
         if: success() || failure()
         run: |
           if [ "${{ steps.before-command.outcome }}" == "failure" ]; then
-            echo "::error step=before-command::Failed to run preparation for ${{ inputs.name }}"; exit 1
+            echo "::error step=before-command::Failed to run preparation for ${{ inputs.image_name }} image build"; exit 1
           fi
-          if [ "${{ steps.run-command.outcome }}" == "failure" ]; then
-            echo "::error step=run-command::Failed to run command ${{ inputs.name }}"; exit 2
+
+          if [ "${{ steps.build-image.outcome }}" == "failure" ]; then
+            echo "::error step=build-image::Failed to build the ${{ inputs.image_name }} image!"; exit 2
           fi
+
+          if [ "${{ steps.test-image.outcome }}" == "failure" ]; then
+            echo "::error step=test-image::Failed to test the ${{ inputs.image_name }} image!"; exit 3
+          if
+
+          if [ "${{ steps.push-image.outcome }}" == "failure" ]; then
+            echo "::error step=push-image::Failed to push the ${{ inputs.image_name }} image!"; exit 4
+          if
+
           if [ "${{ steps.after-command.outcome }}" == "failure" ]; then
-            echo "::warning step=after-command::Failed to run teardown for ${{ inputs.name }}"; exit 0
+            echo "::warning step=after-command::Failed to run teardown for ${{ inputs.image_name }} image build"; exit 0
           fi
