CAT-24489 Added run-commands-template v1

diff --git a/.github/workflows/run-commands-template.yml b/.github/workflows/run-commands-template.yml
--- a/.github/workflows/run-commands-template.yml
+++ b/.github/workflows/run-commands-template.yml
@@ -1,4 +1,4 @@
-name: Template - Run Shell Command
+name: Template - Docker Build/Test/Push
 
 on:
   workflow_call:
@@ -7,34 +7,31 @@ on:
         type: string
         description: 'Environment'
         required: true
-      name:
-        type: string
-        description: 'Run command short name'
-        required: true
-      command:
-        type: string
-        description: 'Run command'
-        required: true
       before_command:
         type: string
-        description: 'Run preparation commands before the commands'
+        description: '(Optional) Command to prepare the environment'
+        required: false
+        default: ''
+      command:
+        type: string
+        description: 'Command to run'
         required: false
         default: ''
       after_command:
         type: string
-        description: 'Run teardown commands after the commands'
+        description: '(Optional) Command to teardown the environment'
         required: false
         default: ''
       assume_aws_role:
         type: boolean
         description: 'Assume AWS role'
         required: false
-        default: false
+        default: true
       ecr_login:
         type: boolean
         description: 'Login to ECR'
         required: false
-        default: false
+        default: true
       parser:
         type: boolean
         description: 'Enable JUnit Parser after runs'
@@ -46,77 +43,147 @@ on:
         required: false
         default: 'outdist/*.xml'
 
+env:
+  APP_NAME: ${{ vars.APP_NAME }}
+
 
 jobs:
-  run-commands:
+  build:
     runs-on: ubuntu-latest
     environment: ${{ inputs.env }}
     steps:
-      - name: Checkout code
+      # Get code, permissions and set environment
+      - name: Code Checkout
         uses: actions/checkout@main
         with:
           fetch-depth: 0
 
-      - name: Assume AWS role
-        if: inputs.assume_aws_role == true
-        id: assume-aws-role
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-region: ${{ vars.AWS_REGION }}
-          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT }}:role/service/${{ vars.AWS_OIDC_ROLE }}
+      # Slack preparation
+      - name: Slack Status file
+        run: |
+          cat > slack_status.txt <<EOL
+          Code Checkout - success
+          AWS Assume Role - $([[ "${{ inputs.assume_aws_role }}" == "true" ]] && echo "pending" || echo "skipped")
+          AWS ECR Login - $([[ "${{ inputs.ecr_login }}" == "true" ]] && echo "pending" || echo "skipped")
+          Preparation Command - $([[ "${{ inputs.before_command }}" != "" ]] && echo "pending" || echo "skipped")
+          Run Command - $([[ "${{ inputs.command }}" != "" ]] && echo "pending" || echo "skipped")
+          Teardown Command - $([[ "${{ inputs.after_command }}" != "" ]] && echo "pending" || echo "skipped")
+          Parsing Results - $([[ "${{ inputs.parser }}" != "" ]] && echo "pending" || echo "skipped")
+          EOL
 
-      - name: Login to Amazon ECR
-        if: steps.assume-aws-role.outcome == 'success' && inputs.ecr_login == true
-        uses: aws-actions/amazon-ecr-login@v1
-
-      - name: Run preparation for ${{ inputs.name }} - ${{ inputs.env }}
-        if: inputs.before_command != ''
-        id: before-command
-        run: ${{ inputs.before_command }}
-
-      - uses: ./.github/actions/slack-message
-        if: always() && ${{ vars.SLACK_CHANNEL_ID }} != ''
+      # Slack Workflow start
+      - name: Slack Workflow start
+        uses: ./.github/actions/slack-message
+        if: ${{ vars.SLACK_CHANNEL_ID }} != ''
         id: slack
         with:
           channel_id: ${{ vars.SLACK_CHANNEL_ID }}
           token: ${{ secrets.SLACK_BOT_TOKEN }}
-          text: "[${{ vars.APP_NAME }} ${{ inputs.env }}] Run ${{ inputs.name }}"
+          text: "${{ env.APP_NAME }} ${{ inputs.env }}"
+          status: Starting up
 
-      - name: Run ${{ inputs.name }} - ${{ inputs.env }}
-        if: inputs.before_command == '' || steps.before-command.outcome == 'success'
-        id: run-command
-        run: ${{ inputs.command }}
+      - name: Assume AWS role
+        if: inputs.assume_aws_role == true
+        uses: aws-actions/configure-aws-credentials@v4
+        id: aws-assume-role
+        with:
+          aws-region: ${{ vars.AWS_REGION }}
+          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT }}:role/service/${{ vars.AWS_OIDC_ROLE }}
 
-      - uses: ./.github/actions/slack-message
+      - run: sed -i 's/AWS Assume Role - .*/AWS Assume Role - ${{ steps.aws-assume-role.outcome }}/' slack_status.txt
+
+      - name: AWS ECR Login
+        if: inputs.ecr_login == true
+        uses: aws-actions/amazon-ecr-login@v1
+        id: aws-ecr-login
+
+      - run: sed -i 's/AWS ECR Login - .*/AWS ECR Login - ${{ steps.aws-ecr-login.outcome }}/' slack_status.txt
+
+      # Preparation Command
+      - name: Preparation Command
+        if: inputs.before_command != ''
+        id: before-command
+        run: ${{ inputs.before_command }}
+      
+      - run: sed -i 's/Preparation Command - .*/Preparation Command - ${{ steps.before-command.outcome }}/' slack_status.txt
+
+      - name: Update Slack
+        uses: ./.github/actions/slack-message
         if: always() && ${{ vars.SLACK_CHANNEL_ID }} != ''
         with:
           channel_id: ${{ vars.SLACK_CHANNEL_ID }}
           token: ${{ secrets.SLACK_BOT_TOKEN }}
-          text: "[${{ vars.APP_NAME }} ${{ inputs.env }}] Run ${{ inputs.name }} - completed"
-          status: ${{ steps.run-command.outcome }}
+          text: "${{ env.APP_NAME }} ${{ inputs.env }}"
           update: ${{ steps.slack.outputs.update }}
 
-      - name: Run teardown for ${{ inputs.name }} - ${{ inputs.env }}
+
+      # Run Command
+      - name: Run Command
+        if: inputs.command != ''
+        id: command
+        run: ${{ inputs.command }}
+
+      - run: sed -i 's/Run Command - .*/Run Command - ${{ steps.command.outcome }}/' slack_status.txt
+
+      - name: Update Slack
+        uses: ./.github/actions/slack-message
+        if: always() && ${{ vars.SLACK_CHANNEL_ID }} != ''
+        with:
+          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
+          token: ${{ secrets.SLACK_BOT_TOKEN }}
+          text: "${{ env.APP_NAME }} ${{ inputs.env }}"
+          update: ${{ steps.slack.outputs.update }}
+
+
+      # Teardown Command
+      - name: Teardown Command
         if: ( success() || failure() ) && inputs.after_command != ''
         id: after-command
         run: ${{ inputs.after_command }}
         continue-on-error: true
 
+      - run: sed -i 's/Teardown Command - .*/Teardown Command - ${{ steps.after-command.outcome }}/' slack_status.txt
+
+      - name: Update Slack
+        uses: ./.github/actions/slack-message
+        if: always() && ${{ vars.SLACK_CHANNEL_ID }} != ''
+        with:
+          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
+          token: ${{ secrets.SLACK_BOT_TOKEN }}
+          text: "${{ env.APP_NAME }} ${{ inputs.env }}"
+          update: ${{ steps.slack.outputs.update }}
+      
+
       - name: JUnit Parser
         if: ( success() || failure() ) && inputs.parser == true
         uses: mikepenz/action-junit-report@v4
+        id: parser
         with:
           report_paths: ${{ inputs.report_paths }}
+      
+      - run: sed -i 's/Parsing Results - .*/Parsing Results - ${{ steps.parser.outcome }}/' slack_status.txt
 
+      - name: Update Slack
+        uses: ./.github/actions/slack-message
+        if: always() && ${{ vars.SLACK_CHANNEL_ID }} != ''
+        with:
+          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
+          token: ${{ secrets.SLACK_BOT_TOKEN }}
+          text: "${{ env.APP_NAME }} ${{ inputs.env }}"
+          update: ${{ steps.slack.outputs.update }}
+
+      # Job End Status
       - name: Set job end status
         if: success() || failure()
         run: |
-          if [ "${{ steps.before-command.outcome }}" == "failure" ]; then
-            echo "::error step=before-command::Failed to run preparation for ${{ inputs.name }}"; exit 1
+          if [[ "${{ steps.before-command.outcome }}" == "failure" ]]; then
+            echo "::error step=before-command::Failed to run preparation command!"; exit 1
           fi
-          if [ "${{ steps.run-command.outcome }}" == "failure" ]; then
-            echo "::error step=run-command::Failed to run command ${{ inputs.name }}"; exit 2
+
+          if [[ "${{ steps.command.outcome }}" == "failure" ]]; then
+            echo "::error step=build-image::Failed to run the command!"; exit 2
           fi
-          if [ "${{ steps.after-command.outcome }}" == "failure" ]; then
-            echo "::warning step=after-command::Failed to run teardown for ${{ inputs.name }}"; exit 0
+
+          if [[ "${{ steps.after-command.outcome }}" == "failure" ]]; then
+            echo "::warning step=after-command::Failed to run teardown command!"; exit 0
           fi
