Fix fail condition

diff --git a/.github/workflows/secrets-scanning.yml b/.github/workflows/secrets-scanning.yml
--- a/.github/workflows/secrets-scanning.yml
+++ b/.github/workflows/secrets-scanning.yml
@@ -42,7 +42,7 @@ jobs:
             extra_args: --debug --only-verified
 
         - name: Scan results on push
-          if: github.event_name == 'push' ||  steps.scanbranch.outcome == 'failure'
+          if: github.event_name == 'push' && steps.scanbranch.outcome == 'failure'
           run: echo "::warning step=scanbranch::secrets found in commit; fix before merging to default branch"; exit 0
 
         # Scan secrets on pull request to the default branch
@@ -58,5 +58,5 @@ jobs:
             extra_args: --debug --only-verified
 
         - name: Scan results on pull request
-          if: github.event_name == 'pull_request' || steps.scansecrets.outcome == 'failure'
-          run: echo "::error step=scansecrets::secrets found in merge request; fix immediately!";exit 1
+          if: github.event_name == 'pull_request' && steps.scansecrets.outcome == 'failure'
+          run: echo "::error step=scansecrets::secrets found in merge request; fix immediately!"; exit 1
