CAT-23668 Setting env vars for steps and failure messages and errors

diff --git a/.github/workflows/secrets-scanning.yml b/.github/workflows/secrets-scanning.yml
--- a/.github/workflows/secrets-scanning.yml
+++ b/.github/workflows/secrets-scanning.yml
@@ -8,11 +8,28 @@ jobs:
             run:
               shell: bash
         steps:
-        - name: Checkout code
-          uses: actions/checkout@v4
-          with:
-            fetch-depth: 0
+        # Prepare environment variables
+        - name: Prepare envs
+          shell: bash
+          run: |
+            if [ "${{ github.event_name }}" == "push" ]; then
+              echo "depth=$(($(jq length <<< '${{ toJson(github.event.commits) }}') + 2))" >> $GITHUB_ENV
+              echo "branch=${{ github.ref_name }}" >> $GITHUB_ENV
+            fi
+            if [ "${{ github.event_name }}" == "pull_request" ]; then
+              echo "depth=$((${{ github.event.pull_request.commits }}+2))" >> $GITHUB_ENV
+              echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
+            fi
+            echo "default_branch=${{ github.event.repository.default_branch }}" >> $GITHUB_ENV
 
+        # Checkout the code using a shallow clone
+        - name: Checkout code
+          uses: actions/checkout@v3
+          with:
+            ref: ${{env.branch}}
+            fetch-depth: ${{env.depth}}
+
+        # Scan secrets on push to the current branch
         - name: Scan secrets on push
           if: github.event_name == 'push'
           id: scanbranch
@@ -21,9 +38,14 @@ jobs:
           with:
             path: ./
             base: ""
-            head: ${{ github.ref_name }}
+            head: ${{env.branch}}
             extra_args: --debug --only-verified
 
+        - name: Scan results on push
+          if: github.event_name == 'push' ||  steps.scanbranch.outcome == 'failure'
+          run: echo "::warning step=scanbranch::secrets found in commit; fix before merging to default branch"; exit 0
+
+        # Scan secrets on pull request to the default branch
         - name: Scan secrets on pull request
           if: github.event_name == 'pull_request'
           id: scansecrets
@@ -31,10 +53,10 @@ jobs:
           continue-on-error: true
           with:
             path: ./
-            base: "${{ github.event.repository.default_branch }}"
-            head: ${{ github.ref_name }}
+            base: ${{env.default_branch}}
+            head: ${{env.branch}}
             extra_args: --debug --only-verified
 
-        - name: Scan Results Status
-          if: steps.scansecrets.outcome == 'failure' ||  steps.scanbranch.outcome == 'failure'
-          run: exit 1
+        - name: Scan results on pull request
+          if: github.event_name == 'pull_request' || steps.scansecrets.outcome == 'failure'
+          run: echo "::error step=scansecrets::secrets found in merge request; fix immediately!";exit 1
